# Generated by Django 4.2 on 2023-09-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_alter_person_property_alter_reading_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.person')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.property')),
            ],
        ),
    ]
