# Generated by Django 4.2 on 2023-09-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='property',
        ),
    ]
