# Generated by Django 4.2 on 2023-09-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_remove_person_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='inhabitants',
            field=models.ManyToManyField(through='water.Residence', to='water.person'),
        ),
    ]
