# Generated by Django 4.2 on 2023-10-11 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water', '0006_rename_inhabitants_property_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='person',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='person',
        ),
        migrations.AddField(
            model_name='reading',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residence',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='persons',
            field=models.ManyToManyField(through='water.Residence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
