# Generated by Django 4.2 on 2023-10-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_remove_reading_person_remove_residence_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='persons',
            new_name='users',
        ),
    ]
